; moOde PHP configuration
display_errors = On
display_startup_errors = On
error_reporting = E_ALL
log_errors = On
error_log = /var/log/php-errors.log

upload_max_filesize = 50M
post_max_size = 50M
memory_limit = 256M
max_execution_time = 300

date.timezone = UTC

; SQLite performance
sqlite3.defensive = 1
