[www]
user = www-data
group = www-data

listen = /run/php/php-fpm.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0660

pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

; PHP settings
php_admin_value[error_log] = /var/log/php-fpm.log
php_admin_flag[log_errors] = on

; moOde-specific settings
php_admin_value[upload_max_filesize] = 50M
php_admin_value[post_max_size] = 50M
php_admin_value[memory_limit] = 256M

; Security
php_admin_value[open_basedir] = /var/www/:/var/local/www/:/tmp/:/var/run/
php_admin_value[disable_functions] = ""
